server:
  port: 8081

spring:
  application:
    name: cloudpaymentservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/learncloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: HUhxc1234!

mybatis:
#  mapper-locations: com.hxc.dao
  type-aliases-package: com.hxc.entities